# Jetson-specific since we don't have a use case on ARM oustide Jetson (maybe Mac? But who uses Mac for Obico server?)

# This will not use cuDNN because no headers included
# should be compatible with Jetpack 4xx
FROM nvcr.io/nvidia/l4t-tensorrt:r10.3.0-devel AS darknet_builder_jetson
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y ca-certificates build-essential gcc g++ cmake git
WORKDIR /
# Lock darknet version for reproducibility
RUN git clone https://github.com/AlexeyAB/darknet && cd darknet && git checkout 59c86222c5387bffd9108a21885f80e980ece234
ENV LIBRARY_PATH="${LIBRARY_PATH}:/usr/local/cuda/targets/aarch64-linux/lib:/usr/local/cuda/targets/aarch64-linux/lib/stubs"
# compile CPU version
WORKDIR /darknet
RUN ln -sf /usr/local/cuda/lib64/stubs/libcuda.so /usr/local/cuda/lib64/libcuda.so
RUN sed -i 's/GPU=0/GPU=1/' Makefile && \
    #sed -i 's/CUDNN=0/CUDNN=1/' Makefile && \
    #sed -i 's/OPENCV=0/OPENCV=1/' Makefile && \
    sed -i 's/LIBSO=0/LIBSO=1/' Makefile

RUN sed -i 's/ARCH= -gencode arch=compute_35,code=sm_35 \\/ARCH= -gencode arch=compute_87,code=[sm_87,compute_87] \\/' Makefile

RUN make -j$(nproc) \
 && cp libdarknet.so libdarknet_gpu.so \
 && cp libdarknet.so libdarknet_cpu.so

# Output image will not have darknet compilation layers to make it smaller
FROM nvcr.io/nvidia/l4t-tensorrt:r10.3.0-runtime AS ml_api_base_jetson

COPY --from=darknet_builder_jetson /darknet /darknet

RUN apt update && apt install --no-install-recommends -y ca-certificates python3-pip wget
#RUN pip install --upgrade pip

WORKDIR /
RUN wget https://nvidia.box.com/shared/static/i7n40ki3pl2x57vyn4u7e9asyiqlnl7n.whl  -O onnxruntime_gpu-1.17.0-cp310-cp310-linux_aarch64.whl 
RUN pip3 install --no-deps --force-reinstall --no-cache-dir \
    onnxruntime_gpu-1.17.0-cp310-cp310-linux_aarch64.whl

# Some hacks to make darknet see cuda libraries. May fail easily
# this is only needed for Jetpack 4x and will not be needed for Jetpack 5
ENV LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/cuda/targets/aarch64-linux/lib"
# https://elinux.org/Jetson_Zoo#ONNX_Runtime
# May be unsafe to use such files, Todo: recompile onnx runtime

WORKDIR /app
RUN pip install opencv_python_headless

ADD requirements.txt ./
RUN pip install -r requirements.txt

EXPOSE 3333